LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libtermux-bootstrap
LOCAL_SRC_FILES := termux-bootstrap-zip.S termux-bootstrap.c
GHOSTEX_BOOTSTRAP_DIR ?= $(LOCAL_PATH)
LOCAL_ASFLAGS += -DGHOSTEX_BOOTSTRAP_AARCH64=\"$(GHOSTEX_BOOTSTRAP_DIR)/bootstrap-aarch64.zip\"
LOCAL_ASFLAGS += -DGHOSTEX_BOOTSTRAP_ARM=\"$(GHOSTEX_BOOTSTRAP_DIR)/bootstrap-arm.zip\"
LOCAL_ASFLAGS += -DGHOSTEX_BOOTSTRAP_I686=\"$(GHOSTEX_BOOTSTRAP_DIR)/bootstrap-i686.zip\"
LOCAL_ASFLAGS += -DGHOSTEX_BOOTSTRAP_X86_64=\"$(GHOSTEX_BOOTSTRAP_DIR)/bootstrap-x86_64.zip\"
include $(BUILD_SHARED_LIBRARY)
